//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from: ProtocolZ.proto
namespace ProtocolZ
{
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"pto_C2S_ReqLogin")]
  public partial class pto_C2S_ReqLogin : global::ProtoBuf.IExtensible
  {
    public pto_C2S_ReqLogin() {}
    
    private uint _player_id = default(uint);
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"player_id", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
    public uint player_id
    {
      get { return _player_id; }
      set { _player_id = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"pto_S2C_ResLogin")]
  public partial class pto_S2C_ResLogin : global::ProtoBuf.IExtensible
  {
    public pto_S2C_ResLogin() {}
    
    private bool _succeed = default(bool);
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"succeed", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(default(bool))]
    public bool succeed
    {
      get { return _succeed; }
      set { _succeed = value; }
    }
    private uint _player_id = default(uint);
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"player_id", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
    public uint player_id
    {
      get { return _player_id; }
      set { _player_id = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"pto_W2G_NtfLogin")]
  public partial class pto_W2G_NtfLogin : global::ProtoBuf.IExtensible
  {
    public pto_W2G_NtfLogin() {}
    
    private uint _player_id = default(uint);
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"player_id", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
    public uint player_id
    {
      get { return _player_id; }
      set { _player_id = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"pto_S2C_NtfKicked")]
  public partial class pto_S2C_NtfKicked : global::ProtoBuf.IExtensible
  {
    public pto_S2C_NtfKicked() {}
    
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"pto_C2S_NtfUpdateOfflineData")]
  public partial class pto_C2S_NtfUpdateOfflineData : global::ProtoBuf.IExtensible
  {
    public pto_C2S_NtfUpdateOfflineData() {}
    
    private string _name = "";
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"name", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string name
    {
      get { return _name; }
      set { _name = value; }
    }
    private uint _max_level = default(uint);
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"max_level", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
    public uint max_level
    {
      get { return _max_level; }
      set { _max_level = value; }
    }
    private uint _pet_quantity = default(uint);
    [global::ProtoBuf.ProtoMember(3, IsRequired = false, Name=@"pet_quantity", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
    public uint pet_quantity
    {
      get { return _pet_quantity; }
      set { _pet_quantity = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"pto_FriendInfo")]
  public partial class pto_FriendInfo : global::ProtoBuf.IExtensible
  {
    public pto_FriendInfo() {}
    
    private uint _player_id = default(uint);
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"player_id", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
    public uint player_id
    {
      get { return _player_id; }
      set { _player_id = value; }
    }
    private string _name = "";
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"name", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string name
    {
      get { return _name; }
      set { _name = value; }
    }
    private uint _max_level = default(uint);
    [global::ProtoBuf.ProtoMember(3, IsRequired = false, Name=@"max_level", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
    public uint max_level
    {
      get { return _max_level; }
      set { _max_level = value; }
    }
    private uint _pet_quantity = default(uint);
    [global::ProtoBuf.ProtoMember(4, IsRequired = false, Name=@"pet_quantity", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
    public uint pet_quantity
    {
      get { return _pet_quantity; }
      set { _pet_quantity = value; }
    }
    private bool _give = default(bool);
    [global::ProtoBuf.ProtoMember(5, IsRequired = false, Name=@"give", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(default(bool))]
    public bool give
    {
      get { return _give; }
      set { _give = value; }
    }
    private bool _receive = default(bool);
    [global::ProtoBuf.ProtoMember(6, IsRequired = false, Name=@"receive", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(default(bool))]
    public bool receive
    {
      get { return _receive; }
      set { _receive = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"pto_C2S_ReqFriendData")]
  public partial class pto_C2S_ReqFriendData : global::ProtoBuf.IExtensible
  {
    public pto_C2S_ReqFriendData() {}
    
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"pto_S2C_ResFriendData")]
  public partial class pto_S2C_ResFriendData : global::ProtoBuf.IExtensible
  {
    public pto_S2C_ResFriendData() {}
    
    private readonly global::System.Collections.Generic.List<pto_FriendInfo> _friend_data = new global::System.Collections.Generic.List<pto_FriendInfo>();
    [global::ProtoBuf.ProtoMember(1, Name=@"friend_data", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<pto_FriendInfo> friend_data
    {
      get { return _friend_data; }
    }
  
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"pto_C2S_ReqAddFriend")]
  public partial class pto_C2S_ReqAddFriend : global::ProtoBuf.IExtensible
  {
    public pto_C2S_ReqAddFriend() {}
    
    private uint _player_id = default(uint);
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"player_id", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
    public uint player_id
    {
      get { return _player_id; }
      set { _player_id = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"pto_S2C_ResAddFriend")]
  public partial class pto_S2C_ResAddFriend : global::ProtoBuf.IExtensible
  {
    public pto_S2C_ResAddFriend() {}
    
    private uint _res = default(uint);
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"res", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
    public uint res
    {
      get { return _res; }
      set { _res = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"pto_C2S_ReqAcceptFriend")]
  public partial class pto_C2S_ReqAcceptFriend : global::ProtoBuf.IExtensible
  {
    public pto_C2S_ReqAcceptFriend() {}
    
    private uint _player_id = default(uint);
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"player_id", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
    public uint player_id
    {
      get { return _player_id; }
      set { _player_id = value; }
    }
    private bool _accept = default(bool);
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"accept", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(default(bool))]
    public bool accept
    {
      get { return _accept; }
      set { _accept = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"pto_S2C_ResAcceptFriend")]
  public partial class pto_S2C_ResAcceptFriend : global::ProtoBuf.IExtensible
  {
    public pto_S2C_ResAcceptFriend() {}
    
    private uint _res = default(uint);
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"res", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
    public uint res
    {
      get { return _res; }
      set { _res = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"pto_C2S_ReqGiveToFriend")]
  public partial class pto_C2S_ReqGiveToFriend : global::ProtoBuf.IExtensible
  {
    public pto_C2S_ReqGiveToFriend() {}
    
    private uint _player_id = default(uint);
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"player_id", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
    public uint player_id
    {
      get { return _player_id; }
      set { _player_id = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"pto_S2C_ResGiveToFriend")]
  public partial class pto_S2C_ResGiveToFriend : global::ProtoBuf.IExtensible
  {
    public pto_S2C_ResGiveToFriend() {}
    
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"pto_C2S_ReqReceiveFromFriend")]
  public partial class pto_C2S_ReqReceiveFromFriend : global::ProtoBuf.IExtensible
  {
    public pto_C2S_ReqReceiveFromFriend() {}
    
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"pto_S2C_ResReceiveFromFriend")]
  public partial class pto_S2C_ResReceiveFromFriend : global::ProtoBuf.IExtensible
  {
    public pto_S2C_ResReceiveFromFriend() {}
    
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"pto_C2S_ReqRemoveFriend")]
  public partial class pto_C2S_ReqRemoveFriend : global::ProtoBuf.IExtensible
  {
    public pto_C2S_ReqRemoveFriend() {}
    
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"pto_S2C_ResRemoveFriend")]
  public partial class pto_S2C_ResRemoveFriend : global::ProtoBuf.IExtensible
  {
    public pto_S2C_ResRemoveFriend() {}
    
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
    [global::ProtoBuf.ProtoContract(Name=@"ProtocolType")]
    public enum ProtocolType
    {
            
      [global::ProtoBuf.ProtoEnum(Name=@"C2S", Value=1)]
      C2S = 1,
            
      [global::ProtoBuf.ProtoEnum(Name=@"S2C", Value=2)]
      S2C = 2,
            
      [global::ProtoBuf.ProtoEnum(Name=@"W2G", Value=3)]
      W2G = 3,
            
      [global::ProtoBuf.ProtoEnum(Name=@"G2W", Value=4)]
      G2W = 4
    }
  
    [global::ProtoBuf.ProtoContract(Name=@"LoginProtocolID")]
    public enum LoginProtocolID
    {
            
      [global::ProtoBuf.ProtoEnum(Name=@"LoginProtocolIDBegin", Value=1000)]
      LoginProtocolIDBegin = 1000,
            
      [global::ProtoBuf.ProtoEnum(Name=@"C2S_ReqLogin", Value=1001)]
      C2S_ReqLogin = 1001,
            
      [global::ProtoBuf.ProtoEnum(Name=@"S2C_ResLogin", Value=1002)]
      S2C_ResLogin = 1002,
            
      [global::ProtoBuf.ProtoEnum(Name=@"W2G_NtfLogin", Value=1003)]
      W2G_NtfLogin = 1003,
            
      [global::ProtoBuf.ProtoEnum(Name=@"S2C_NtfKicked", Value=1004)]
      S2C_NtfKicked = 1004,
            
      [global::ProtoBuf.ProtoEnum(Name=@"C2S_NtfUpdateOfflineData", Value=1005)]
      C2S_NtfUpdateOfflineData = 1005,
            
      [global::ProtoBuf.ProtoEnum(Name=@"LoginProtocolIDEnd", Value=1999)]
      LoginProtocolIDEnd = 1999
    }
  
    [global::ProtoBuf.ProtoContract(Name=@"FriendProtocolID")]
    public enum FriendProtocolID
    {
            
      [global::ProtoBuf.ProtoEnum(Name=@"FriendProtocolIDBegin", Value=2000)]
      FriendProtocolIDBegin = 2000,
            
      [global::ProtoBuf.ProtoEnum(Name=@"C2S_ReqFriendData", Value=2001)]
      C2S_ReqFriendData = 2001,
            
      [global::ProtoBuf.ProtoEnum(Name=@"S2C_ResFriendData", Value=2002)]
      S2C_ResFriendData = 2002,
            
      [global::ProtoBuf.ProtoEnum(Name=@"C2S_ReqAddFriend", Value=2003)]
      C2S_ReqAddFriend = 2003,
            
      [global::ProtoBuf.ProtoEnum(Name=@"S2C_ResAddFriend", Value=2004)]
      S2C_ResAddFriend = 2004,
            
      [global::ProtoBuf.ProtoEnum(Name=@"C2S_ReqAcceptFriend", Value=2005)]
      C2S_ReqAcceptFriend = 2005,
            
      [global::ProtoBuf.ProtoEnum(Name=@"S2C_ResAcceptFriend", Value=2006)]
      S2C_ResAcceptFriend = 2006,
            
      [global::ProtoBuf.ProtoEnum(Name=@"C2S_ReqGiveToFriend", Value=2007)]
      C2S_ReqGiveToFriend = 2007,
            
      [global::ProtoBuf.ProtoEnum(Name=@"S2C_ResGiveToFriend", Value=2008)]
      S2C_ResGiveToFriend = 2008,
            
      [global::ProtoBuf.ProtoEnum(Name=@"C2S_ReqReceiveFromFriend", Value=2009)]
      C2S_ReqReceiveFromFriend = 2009,
            
      [global::ProtoBuf.ProtoEnum(Name=@"S2C_ResReceiveFromFriend", Value=2010)]
      S2C_ResReceiveFromFriend = 2010,
            
      [global::ProtoBuf.ProtoEnum(Name=@"C2S_ReqRemoveFriend", Value=2011)]
      C2S_ReqRemoveFriend = 2011,
            
      [global::ProtoBuf.ProtoEnum(Name=@"S2C_ResRemoveFriend", Value=2012)]
      S2C_ResRemoveFriend = 2012,
            
      [global::ProtoBuf.ProtoEnum(Name=@"FriendProtocolIDEnd", Value=2999)]
      FriendProtocolIDEnd = 2999
    }
  
}